### ISSUE TITLE
Не всегда парсит все сайты

### ISSUE THREAD

**Issue by niktimmans** [Romancikh/ISPPR_bot#1]
https://github.com/Romancikh/ISPPR_bot/blob/f08966bd12d8d854d84cd46cfb4c2de4baa76b73/venv/Scripts/main/bot.py#L33

Данные должны быть подгружены асинхронно. Попробовать добавить async.

**Comment by Romancikh** [comment]
![image](https://user-images.githubusercontent.com/49481487/144495332-e8d2a511-9aa6-4d66-9068-b5d9e4996467.png)
